version: 2
updates:
  - package-ecosystem: npm
    directory: /
    target-branch: develop
    schedule:
      interval: weekly
      day: monday
    open-pull-requests-limit: 5
    groups:
      non-major:
        patterns:
          - "*"
        update-types:
          - minor
          - patch
    ignore:
      - dependency-name: "@playwright/test"
        update-types:
          - version-update:semver-major
      - dependency-name: "supabase"
        update-types:
          - version-update:semver-major
